import Head from "next/head";

import { Container, Input, Button, Text } from "@styles/index";

import { HomeMain, HomeHeader, HomeFormSearch } from "./styles";

import { ResultWord } from "@components/ResultWord";
import { WordsSection } from "./components/WordsSection";
import { useContext, useRef } from "react";
import { Toast } from "@components/Toast";
import { FavoritesArea } from "./components/FavoritesArea";
import { FavoritesWordsContext } from "@providers/wordsProvider";

export default function Home() {
  const inputSearchRef = useRef<HTMLInputElement>(null);

  const { getAPIWord, error, wordCurrent, setError } = useContext(
    FavoritesWordsContext
  );

  return (
    <>
      <Head>
        <title>My Words</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeMain>
        <Container>
          <Toast
            control={error}
            setControl={setError}
            title="Ops! Word not found"
            description="Can't find that word in our database"
          />

          <HomeHeader>
            <Text size="lg" weight="semibold">
              MyWords
            </Text>
            <FavoritesArea />
          </HomeHeader>
          <HomeFormSearch>
            <Input
              placeholder="Type the word here..."
              css={{ width: "85%", "@bp1": { width: "100%" } }}
              ref={inputSearchRef}
            />
            <Button
              size="lg"
              type="brand"
              css={{ width: "15%", "@bp1": { width: "100%" } }}
              onClick={() => getAPIWord(inputSearchRef?.current.value)}
            >
              Search
            </Button>
          </HomeFormSearch>
          <ResultWord
            word={wordCurrent?.word}
            text={wordCurrent?.text}
            audio={wordCurrent?.audio}
            type={wordCurrent?.type}
            id={wordCurrent.id}
            phraseExample={wordCurrent?.phraseExample}
          />
          <WordsSection />
        </Container>
      </HomeMain>
    </>
  );
}
