import Head from "next/head";

import { Text } from "@styles/texts";
import { Button } from "@styles/buttons";
import { Container } from "@styles/stitches.config";
import { HomeMain, HomeHeader } from "./styles";
import { FaHeart } from "react-icons/fa";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Words</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeMain>
        <Container>
          <HomeHeader>
            <Text size="lg" weight="semibold">
              MyWords
            </Text>
            <Button withIcon>
              <FaHeart />
              Favorites
            </Button>
          </HomeHeader>
        </Container>
      </HomeMain>
    </>
  );
}
