import Head from "next/head";

import { Container, Input, Button, Text } from "@styles/index";

import { HomeMain, HomeHeader, HomeFormSearch } from "./styles";

import { ResultWord } from "@components/ResultWord";
import { WordsSection } from "./components/WordsSection";
import { useContext, useEffect, useRef } from "react";
import { Toast } from "@components/Toast";
import { FavoritesArea } from "./components/FavoritesArea";
import { FavoritesWordsContext } from "@providers/wordsProvider";

export default function Home() {

  const inputSearchRef = useRef<HTMLInputElement>(null);

  const { getAPIWord, error, word, setError } = useContext(FavoritesWordsContext)

  useEffect(() => {
    getAPIWord("word", 1668384142161.6328);
  }, []);

  return (
    <>
      <Head>
        <title>My Words</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeMain>
        <Container>
          <Toast
            control={error}
            setControl={setError}
            title="Ops! Word not found"
            description="Can't find that word in our database"
          />

          <HomeHeader>
            <Text size="lg" weight="semibold">
              MyWords
            </Text>
            <FavoritesArea />
          </HomeHeader>
          <HomeFormSearch>
            <Input
              placeholder="Type the word here..."
              css={{ width: "85%" }}
              ref={inputSearchRef}
            />
            <Button
              size="lg"
              type="brand"
              css={{ width: "15%" }}
              onClick={() => getAPIWord(inputSearchRef?.current.value)}
            >
              Search
            </Button>
          </HomeFormSearch>
          <ResultWord
            world={word?.word}
            text={word?.text}
            audio={word?.audio}
            type={word?.type}
            id={word.id}
            phraseExample={word?.phraseExample}
          />
          <WordsSection />
        </Container>
      </HomeMain>
    </>
  );
}
